In [110]:
import numpy as np
burgerdata={'data':np.array([[ 5.1,  3.5,  1.4,  0.2],
                             [ 4.9,  3. ,  1.4,  0.2],
                             [ 4.7,  3.2,  1.3,  0.2],
                             [ 4.6,  3.1,  1.5,  0.2],
                             [ 5. ,  3.6,  1.4,  0.2],
                             [ 5.4,  3.9,  1.7,  0.4],
                             [ 4.6,  3.4,  1.4,  0.3],
                             [ 5. ,  3.4,  1.5,  0.2],
                             [ 4.4,  2.9,  1.4,  0.2],
                             [ 4.9,  3.1,  1.5,  0.1],
                             [ 5.4,  3.7,  1.5,  0.2],
                             [ 4.8,  3.4,  1.6,  0.2],
                             [ 4.8,  3. ,  1.4,  0.1],
                             [ 4.3,  3. ,  1.1,  0.1],
                             [ 5.8,  4. ,  1.2,  0.2],
                             [ 5.7,  4.4,  1.5,  0.4],
                             [ 5.4,  3.9,  1.3,  0.4],
                             [ 5.1,  3.5,  1.4,  0.3],
                             [ 5.7,  3.8,  1.7,  0.3],
                             [ 5.1,  3.8,  1.5,  0.3],
                             ]),
            'target':np.array([0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1]),
            'target_names':np.array(['Veg-Burger','non-veg Burger']),
            'feature_names':['ingredients-1','ingredients-2','ingredients-3','ingredients-4']}


In [111]:
x_input=burgerdata['data']
y_target=burgerdata['target']

In [112]:
x_input[0,1]

3.5

In [113]:
x_input[0,:]

array([ 5.1,  3.5,  1.4,  0.2])

In [114]:
#random
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x_input,y_target,test_size=.30,random_state=101)

In [115]:
x_train.shape

(14, 4)

In [116]:
x_test.shape

(6, 4)

In [117]:
x_train

array([[ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.5,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 4.8,  3.4,  1.6,  0.2]])

In [118]:
y_train

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1])

In [119]:
x_test.shape

(6, 4)

In [120]:
y_test.shape

(6,)

In [121]:
from sklearn.neighbors import KNeighborsClassifier

teacher=KNeighborsClassifier()


In [122]:
learner=teacher.fit(x_train,y_train)
ya=y_test
#yaha pr hum log x_test dekar value predict krne koshish kr rahe hai xtest se niklegi
#yp==>>predicted value
#chahe jo ho jaye target or feature String ya character nii ho sakte hai
#isme humlog string data kyuki 5 data ka mathematical calcultion humesha float ya int me hoga
yp=learner.predict(x_test)


In [123]:
ya

array([0, 0, 0, 0, 1, 1])

In [124]:
yp

array([0, 0, 0, 0, 1, 1])

In [125]:
from sklearn.metrics import accuracy_score
score= accuracy_score(ya,yp)*100

In [126]:
score


100.0