In [8]:
from sklearn import datasets

In [10]:
digitdata=datasets.load_digits()
digitdata.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [13]:
#separating data
x_input=digitdata.data
y_out=digitdata.target


In [14]:
#split
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x_input,y_out,test_size=.30,random_state=101)

In [22]:
x_train.shape

(1257, 64)

In [23]:
y_train.shape

(1257,)

In [24]:
from sklearn.svm import SVC

In [77]:
teacher=SVC(gamma=.001)
learner=teacher.fit(x_train,y_train)
yp=learner.predict(x_test)
ya=y_test

In [78]:
from sklearn.metrics import accuracy_score

In [79]:
score=accuracy_score(ya,yp)*100

In [80]:
score

99.259259259259252

In [83]:
learner.predict(x_test[1])

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([4])

In [84]:
ya[1]

4

In [86]:
from scipy import misc

In [87]:
test_image=misc.imread(r"5.jpg")

In [88]:
test_image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ..., 
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ..., 
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ..., 
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ..., 
       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ..., 
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ..., 
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ..., 
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [89]:
test_image.shape

(256, 256, 3)

In [90]:
test_image88=misc.imresize(test_image,(8,8))

In [91]:
test_image88

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [28, 28, 28],
        [27, 27, 27],
        [26, 26, 26],
        [12, 12, 12],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  1,  1],
        [31, 31, 31],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  1,  1],
        [35, 35, 35],
        [20, 20, 20],
        [24, 24, 24],
        [ 8,  8,  8],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [12, 12, 12],
        [14, 14, 14],
        [12, 12, 12],
        [30, 30, 30],
        [ 4,  4,  4],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [23, 23, 23],
        [10, 10, 10],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 3,  3,  3],


In [92]:
test_image88.shape

(8, 8, 3)

In [94]:
digitdata.data.dtype

dtype('float64')

In [95]:
test_image88.dtype


dtype('uint8')

In [97]:
test_image8864=test_image88.astype(digitdata.data.dtype)

In [99]:
test_image8864.dtype

dtype('float64')

In [101]:
test_image8864

array([[[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [ 28.,  28.,  28.],
        [ 27.,  27.,  27.],
        [ 26.,  26.,  26.],
        [ 12.,  12.,  12.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  1.,   1.,   1.],
        [ 31.,  31.,  31.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  1.,   1.,   1.],
        [ 35.,  35.,  35.],
        [ 20.,  20.,  20.],
        [ 24.,  24.,  24.],
        [  8.,   8.,   8.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [ 12.,  12.,  12.],
        [ 14.,  14.,  14.],
        [ 12.,  12.,  12.],
        [ 30.,  30.,  30.],
        [  4.,   4.,   4.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0

In [102]:
#scaling dwnscling
test_image886416=misc.bytescale(test_image8864,high=16,low=0)

In [103]:
test_image886416

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [12, 12, 12],
        [11, 11, 11],
        [11, 11, 11],
        [ 5,  5,  5],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [13, 13, 13],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [15, 15, 15],
        [ 8,  8,  8],
        [10, 10, 10],
        [ 3,  3,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 5,  5,  5],
        [13, 13, 13],
        [ 2,  2,  2],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [10, 10, 10],
        [ 4,  4,  4],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1],


In [104]:
test_image886416.dtype

dtype('uint8')

In [107]:
test_image88641664=test_image886416.astype(digitdata.data.dtype)

In [108]:
test_image88641664

array([[[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [ 12.,  12.,  12.],
        [ 11.,  11.,  11.],
        [ 11.,  11.,  11.],
        [  5.,   5.,   5.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [ 13.,  13.,  13.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [ 15.,  15.,  15.],
        [  8.,   8.,   8.],
        [ 10.,  10.,  10.],
        [  3.,   3.,   3.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  5.,   5.,   5.],
        [  6.,   6.,   6.],
        [  5.,   5.,   5.],
        [ 13.,  13.,  13.],
        [  2.,   2.,   2.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0

In [109]:
test_image88641664.dtype

dtype('float64')

In [111]:
test_image88641664.shape

(8, 8, 3)

In [113]:
x_test_image=[]

In [114]:
for i in test_image88641664:
    for j in i:
        x_test_image.append(sum(i/3.0))

In [118]:
len(x_test_image)

64

In [122]:
import numpy as np
x_test_array=np.array(x_test_image)

In [123]:
x_test_image

[array([ 13.,  13.,  13.]),
 array([ 13.,  13.,  13.]),
 array([ 13.,  13.,  13.]),
 array([ 13.,  13.,  13.]),
 array([ 13.,  13.,  13.]),
 array([ 13.,  13.,  13.]),
 array([ 13.,  13.,  13.]),
 array([ 13.,  13.,  13.]),
 array([ 4.33333333,  4.33333333,  4.33333333]),
 array([ 4.33333333,  4.33333333,  4.33333333]),
 array([ 4.33333333,  4.33333333,  4.33333333]),
 array([ 4.33333333,  4.33333333,  4.33333333]),
 array([ 4.33333333,  4.33333333,  4.33333333]),
 array([ 4.33333333,  4.33333333,  4.33333333]),
 array([ 4.33333333,  4.33333333,  4.33333333]),
 array([ 4.33333333,  4.33333333,  4.33333333]),
 array([ 12.,  12.,  12.]),
 array([ 12.,  12.,  12.]),
 array([ 12.,  12.,  12.]),
 array([ 12.,  12.,  12.]),
 array([ 12.,  12.,  12.]),
 array([ 12.,  12.,  12.]),
 array([ 12.,  12.,  12.]),
 array([ 12.,  12.,  12.]),
 array([ 10.33333333,  10.33333333,  10.33333333]),
 array([ 10.33333333,  10.33333333,  10.33333333]),
 array([ 10.33333333,  10.33333333,  10.33333333]),
 arr