In [1]:
import numpy as np

In [4]:
X=np.array([[1],[2],[3],[4]])

In [5]:
X.shape

(4, 1)

In [6]:
Y=np.array([6,5,7,10])

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
teacher=LinearRegression()

In [9]:
learner=teacher.fit(X,Y)

In [10]:
learner.predict([[1]])

array([ 4.9])

In [12]:
learner.coef_

array([ 1.4])

In [13]:
learner.intercept_

3.5000000000000013

In [14]:
learner.predict([[8]])

array([ 14.7])