In [1]:
import numpy as np

In [11]:
X=np.array([1,2,3,4,5])

In [12]:
X=X.reshape(-1,1)

In [13]:
X.shape

(5, 1)

In [14]:
X


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [22]:
Y=np.array([1,3,2,3,5])

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
teacher=LinearRegression()

In [33]:
learner=teacher.fit(X,Y)

In [34]:
learner.predict([[1]])

array([ 1.2])

In [35]:
learner.coef_

array([ 0.8])

In [36]:
learner.predict([[2]])

array([ 2.])

In [37]:
learner.intercept_

0.39999999999999991