In [1]:
import numpy as np

In [4]:
myarray=np.array([11,22,33,44,55,66,77,88,99])

In [5]:
print(type(myarray))

<class 'numpy.ndarray'>


In [6]:
len(myarray)

9

In [7]:
myarray.shape

(9,)

In [8]:
myarray.size

9

In [9]:
myarray.sum()

495

In [10]:
myarray.mean()

55.0

In [12]:
myarray.max()

99

In [14]:
myarray.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [15]:
myarray[0]

11

In [16]:
myarray[-1]

99

In [17]:
myarray[1:-1:2]

array([22, 44, 66, 88])

In [23]:
array_2d=np.array([[1,2,3],[5,6,7],[8,9,0]])


In [24]:
array_2d.size


9

In [25]:
array_2d.ndim

2

In [26]:
array_2d.shape

(3, 3)

In [27]:
array_2d

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [28]:
array_2d.sum

<function ndarray.sum>

In [29]:
array_2d.sum()

41

In [30]:
sum(array_2d)

array([14, 17, 10])

In [31]:
array_2d.sum(axis=0)

array([14, 17, 10])

In [32]:
array_2d.sum(axis=1)

array([ 6, 18, 17])

In [33]:
array_2d[0][1]

2

In [34]:
array_2d[0]

array([1, 2, 3])

In [35]:
array_2d[0,:]

array([1, 2, 3])

In [36]:
array_2d[2,:]

array([8, 9, 0])

In [38]:
array_2d[:,2]

array([3, 7, 0])

In [40]:
array_2d[:2:,1::]

array([[2, 3],
       [6, 7]])

In [42]:
array_2d[:3:2,0:3:2]

array([[1, 3],
       [8, 0]])

In [44]:
array_2d[0:3:2,0:3:2]

array([[1, 3],
       [8, 0]])

In [48]:
array_2d

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [50]:
array_2d[0:3:1,1:2:]

array([[2],
       [6],
       [9]])

In [51]:
array_2d.diagonal()

array([1, 6, 0])

In [60]:
array_2d[:,::-1]

array([[3, 2, 1],
       [7, 6, 5],
       [0, 9, 8]])

In [61]:
array_2d[::-1,::-1]

array([[0, 9, 8],
       [7, 6, 5],
       [3, 2, 1]])