In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
len(a)

9

In [4]:
a.shape

(9,)

In [5]:
b=a.reshape(3,3)

In [6]:
len(b)

3

In [7]:
b.shape

(3, 3)

In [8]:
b.size

9

In [9]:
b.ndim

2

In [10]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
c=[1,2,3,4,5,6,7,8,9]

In [12]:
type(c)

list

In [14]:
type(b)

numpy.ndarray

In [15]:
b=c.reshape(3,3)

AttributeError: 'list' object has no attribute 'reshape'

In [16]:
cc=np.array(c)

In [19]:
b=cc.reshape(3,3)

In [20]:
b=cc.reshape(-3,2)

ValueError: total size of new array must be unchanged

In [22]:
b=cc.reshape(-3,1)

In [23]:
b.ndim

2

In [24]:
d=np.array([1,2,3,4,5,6,7,8,9,0])

In [25]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [26]:
e=d.reshape(5,2)

In [27]:
e

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [30]:
ee=np.resize(d,(3,6))
ee

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2],
       [3, 4, 5, 6, 7, 8]])

In [32]:
a_z=np.zeros([3,3])
a_z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
a_o=np.ones([4,4])
a_o

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [36]:
print("value of a_z is\n {} \n value of a_o is\n{}\n".format(a_z,a_o))

value of a_z is
 [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 
 value of a_o is
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]



In [38]:
a_i=np.eye(3)

In [39]:
print("value of a_z is\n {} \nvalue of a_o is\n{}\nvalue of a_i is\n{}".format(a_z,a_o,a_i))

value of a_z is
 [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 
value of a_o is
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
value of a_i is
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [41]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [42]:
b=np.arange(2,15,3)

In [43]:
b

array([ 2,  5,  8, 11, 14])

In [45]:
c=np.arange(1,10)
d=c.reshape([3,3])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
e=np.linspace(0,30,15)

e

array([  0.        ,   2.14285714,   4.28571429,   6.42857143,
         8.57142857,  10.71428571,  12.85714286,  15.        ,
        17.14285714,  19.28571429,  21.42857143,  23.57142857,
        25.71428571,  27.85714286,  30.        ])

In [50]:
f=np.linspace(0,30,3)
f

array([  0.,  15.,  30.])

In [53]:
#random
r=np.random.rand()
r
#print a random number b/w 0 to 1

0.7828088042327422

In [56]:
s=np.random.rand(6)
s

array([ 0.63253558,  0.01511421,  0.52788537,  0.75243906,  0.56585866,
        0.15676169])

In [57]:
r=np.random.random_sample()
r

0.5046158817283228

In [58]:
r=np.random.randn()
r

-1.348354598720508

In [60]:
r=np.random.randint(4,10,4)
r

array([8, 9, 6, 6])

In [61]:
r=np.random.randint(4,10,(3,3))
r

array([[8, 5, 6],
       [6, 4, 6],
       [7, 7, 5]])

In [73]:
np.random.seed
r=np.random.randint(0,10,(3,3))
r

array([[4, 9, 1],
       [2, 2, 8],
       [0, 0, 3]])

In [68]:
len(r)

3

In [69]:
r.itemsize

4

In [70]:
r.dtype

dtype('int32')